### ISSUE TITLE
Support RAML 1.0 when the raml parser 2 is out of beta

### ISSUE THREAD

**Issue by JonathanMontane** [luckymarmot/Paw-RAMLImporter#1]
Currently, we only support RAML up to the v0.8 version.
The RAML org recently introduced RAML v1.0, that has a few improvements on RAML v0.8, some of which are not backward compatible. (e.g. [dataTypes](https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#whats-new-and-different-in-raml-10), now used instead of formParameters)

Once the raml parser for the v1 is stable enough, we should also support it.

**Comment by alecthomas** [comment]
Is [this](https://github.com/raml-org/raml-js-parser-2) the parser you're using? It seems like it may be out of beta now.

**Comment by JonathanMontane** [comment]
@alecthomas, awesome! Thanks for the notice, I'll look into it! Don't expect a RAML v1.0 importer for next week though ;)

**Comment by lonniev** [comment]
How about within 2 weeks then, if not next week?

**Comment by sebastianf** [comment]
any news here?

**Comment by mittsh** [comment]
We've made some start on RAML 1.0 support (@jonathanmontane made a start on it), but it's not finished yet. You may use [API Transformer](https://apimatic.io/transformer) to convert your RAML 1.0 files to 0.8 in the meantime.

Of course we're going to support it in anyway! Sorry for the delay…

**Comment by lonniev** [comment]
Downgrading RAML 1.0 to RAML 0.8 is not a helpful suggestion. ;-) Just keep the focus on getting support for RAML 1 implemented and let us know when that is ready.

-- 
Lonnie VanZandt
303-900-3048

On 11 November 2016 at 09:34:59, Micha Mazaheri (notifications@github.com) wrote:

We've made some start on RAML 1.0 support (@jonathanmontane made a start on it), but it's not finished yet. You may use API Transformer to convert your RAML 1.0 files to 0.8 in the meantime.

Of course we're going to support it in anyway! Sorry for the delay…

**Comment by mittsh** [comment]
It was only a suggestion so you guys can import your RAML files into Paw right now… :) It of course doesn't remplace a real support for it, which will come for sure.

**Comment by lonniev** [comment]
Kind of like a Ruth Chris waiter saying, “we’re all out of steak tonight sir. But we can make you a bologna sandwich if you really are hungry.”

I’ll keep waiting for the filet mignon. ;-)

-- 
Lonnie VanZandt
303-900-3048

On 11 November 2016 at 11:37:01, Micha Mazaheri (notifications@github.com) wrote:

It was only a suggestion so you guys can import your RAML files into Paw right now… :) It of course doesn't remplace a real support for it, which will come for sure.

**Comment by kvnvelasco** [comment]
So. It's Feb 2017. Any news on this?

**Comment by JonathanMontane** [comment]
@kvnvelasco We're actually working on it, and we're quite close to completion! We're going to use quite a few new features that are coming with the next paw release, so it should come around the same time (in the next two weeks)

**Comment by lonniev** [comment]
Just to suck up: if it is as awesome as the rest of Paw, it will be
outstanding.

Finish strong and quickly; we’re waiting for it.



-- 
Lonnie VanZandt
303-900-3048

On 21 February 2017 at 02:10:08, Jonathan Montane (notifications@github.com)
wrote:

@kvnvelasco <https://github.com/kvnvelasco> We're actually working on it,
and we're quite close to completion! We're going to use quite a few new
features that are coming with the next paw release, so it should come
around the same time (in the next two weeks)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/luckymarmot/Paw-RAMLImporter/issues/1#issuecomment-281285531>,
or mute the thread

**Comment by nitecon** [comment]
Any completion date scheduled for this?  I'd like to give paw a shot and maybe show to my team but this is a pretty major blocker.

**Comment by mittsh** [comment]
@Nitecon We're working on a major update of Paw – with nice changes on the app, bringing more compatibility with Swagger and RAML. As part of this, we're going to update the RAML importer to support RAML 1.0. It should come in a matter of weeks. Thanks 😄

**Comment by sichvoge** [comment]
Any updates @mittsh?

**Comment by JonathanMontane** [comment]
@sichvoge https://paw.cloud/extensions/RAML1Importer

ALSO: if you want to contribute to the project behind it, it's called API-Flow, which is an API Format converter.
https://github.com/luckymarmot/API-Flow

**Comment by sichvoge** [comment]
@JonathanMontane have you had a chance to look at MuleSoft's OAS/RAML converter [here](https://github.com/mulesoft/oas-raml-converter)? Maybe it could help validating your RAML <> OAS conversions.
